application: david-buxton-test
version: dev
runtime: python27
api_version: 1
threadsafe: true

libraries:
  - name: ssl
    version: "2.7"

handlers:
  - url: /_ah/.*
    script: dbux.wsgi.application
    login: admin

  - url: /tasks/.*
    script: dbux.wsgi.application
    login: admin

  - url: /.*
    script: dbux.wsgi.application

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$

  - ^libs/.*\.dist-info/
