application: david-buxton-test
version: dev
runtime: python27
api_version: 1
threadsafe: true

builtins:
  - deferred: on

handlers:
  - url: /tasks/.*
    script: wsgi.app
    login: admin
    secure: always

  - url: /site.css
    static_files: site.css
    upload: site.css
    secure: always

  - url: /.*
    script: wsgi.app
    secure: always

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$

  - ^.*\.(dist|egg)-info/
