application: david-buxton-test
version: dev
runtime: python27
api_version: 1
threadsafe: true

builtins:
  - deferred: on

handlers:
  - url: /_ah/.*
    script: wsgi.app
    login: admin

  - url: /tasks/.*
    script: wsgi.app
    login: admin

  - url: /.*
    script: wsgi.app

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$

  - ^libs/.*\.dist-info/
